default: &default
  adapter: postgresql

development:
  adapter: postgresql
  database: rantly_development

test:
  adapter: postgresql
  database: rantly_test

production:
  adapter: postgresql
  database: rantly_development
